### ISSUE TITLE
deployment documentation

### ISSUE THREAD

**Issue by szuecs** [zalando-incubator/fabric-gateway#5]
There is no deployment configuration, YAML files in `deploy` folder have variables, that need to be replaced by the user.
I would suggest to have a `docs/` folder and link to installation docs from the readme.

**Comment by irishshagua** [comment]
@herojan do you think this is something that can be closed after the merge of https://github.com/zalando-incubator/fabric-gateway/pull/8?

**Comment by szuecs** [comment]
Yes
