### ISSUE TITLE
Support the skipper fadeIn filter

### ISSUE THREAD

**Issue by rafaelsbz** [zalando-incubator/fabric-gateway#70]
Hi folks @Fabric

I would like to suggest adding support for configuring the Skipper [fadeIn filter](https://opensource.zalando.com/skipper/reference/filters/#fadein). This filter is highly useful on kubernetes deployments using skipper as Ingress, as it allows traffic to new pods to be switched gradually (i.e. faded in). This helps mitigating startup issues such as latency spikes caused by JVM JIT compilation and/or non-warmed-up connection pools.

**Comment by irishshagua** [comment]
> Maybe better to just allow an annotation to pass skipper filters in general.

I'm going to look at this today. One concern with a general pass through of filters is the potential for filters to combine in a way that would end up being dangerous for backends. An example would be `dropRequestHeader`; when experimenting with this previously, dropping the Auth header caused all kinds of issues as it was needed by other filters. One of the _selling points_ of gateway is that it enables the functionality while preventing you from shooting yourself in the foot. 

Another concern about a general annotation is that it would prevent us from applying the filter to specific routes. Most other features are applicable globally and at the specific route level.

It might make sense for a small allow list of filters to be applied generically and would definitely be the simplest change to make (no requirement for updates to the CRD). Will work on an impl today and see what the implications are anyways.

**Comment by irishshagua** [comment]
Closing this as support for adding fadeIn filter was added in latest release of gateway

**Comment by rafaelsbz** [comment]
That was an extremely quick turnaround. Thanks and well done! :)
