### ISSUE TITLE
Support the `backendRateLimit` feature

### ISSUE THREAD

**Issue by andrewhowdencom** [zalando-incubator/fabric-gateway#73]
The skipper team have been working on a new filter, called `backendRateLimit`, designed to address some issues in calculating rate limits for services that autoscale. Broadly, the problem is that the existing rate limits (such as clusterClientRateLimit) define an arbitrary rate limit for the _entire service_ — all discovered endpoints for that service.

For the majority of services they can horizontally scale, and the throughput a service is able to deliver is a function of how many replicas that service is operating with (as well as certain constants; database through capacity for example). 

To facilitate this ambiguity, as well as to make the calculation of the "final practical" rate limit much easier, the skipper team implemented `backendRateLimit` — a limit to how many requests a single destination replica can process over a sliding window.

For applications that are behind "fabric gateway", they currently cannot (easily) use this feature. Given this, this feature request is to expose the feature, similar to how `clusterClientRateLimit` is now implemented. 

Some additional reading is available at:

1. https://opensource.zalando.com/skipper/reference/filters/#backendratelimit
2. https://github.com/zalando/skipper

**Comment by szuecs** [comment]
This might be easily supported by copying skipper filter annotations from fabric CRD to the created ingress.
This would only allow to set a single value for the whole API group, but seems reasonable enough to me at least without too much work and as a very generic solution.
Of course well integrated would be even better but we have not much experience right now to suggest a best practice.

**Comment by cjbooms** [comment]
This filter has now been added to the allow-list in all Zalando clusters. It can be configured as follows:
```
kind: FabricGateway
metadata:
  annotations:
    fabric/additional-filters: backendRatelimit("global", 1, "10s", 418)
```

### Warning - Usage of 429 may have varying response content-type

For routes with `x-fabric-ratelimits` applied: 
```
HTTP/2 429
date: Wed, 16 Jun 2021 10:07:25 GMT
content-type: application/problem+json
content-length: 193
server: Skipper

{"title": "Rate limit exceeded", "detail": "See the x-rate-limit header for your rate limit per minute, and the retry-after header for how many seconds to wait before retrying.", "status": 429}
```

For routes without any `x-fabric-ratelimits` applied: 
```
HTTP/2 429
date: Wed, 16 Jun 2021 10:06:05 GMT
content-length: 0
server: Skipper
```
